### ISSUE TITLE
Fatal Error 

### ISSUE THREAD

**Issue by mrmidwest** [dlnetworks/twittercast#8] opened 2017-01-31 02:55 UTC
Hello, 

i am running shoutcast_V1, and I get this error:

> Fatal error: Uncaught exception 'EpiTwitterException' in /home/content/66/4294166/html/EpiTwitter.php:279 Stack trace: #0 /home/content/66/4294166/html/EpiTwitter.php(226): EpiTwitterException::raise(Object(EpiCurlManager), false) #1 /home/content/66/4294166/html/EpiTwitter.php(127): EpiTwitterJson->__get('response') #2 /home/content/66/4294166/html/EpiTwitter.php(44): EpiTwitter->request('POST', '/statuses/updat...', Array) #3 /home/content/66/4294166/html/shoutcast_v1.php(84): EpiTwitter->post('/statuses/updat...', Array) #4 {main} thrown in /home/content/66/4294166/html/EpiTwitter.php on line 279

are you aware what or how to fix this?

**Comment by dlnetworks** [comment] 2017-01-31 11:33
it looks like some of the text is missing from that output... 

generally the cause will be in the exception error msg

such as

`PHP Fatal error: Uncaught exception 'EpiTwitterForbiddenException' with message '{"errors":[{"code":187,"message":"Status is a duplicate."}]}' in `

do you see a title when viewing the page in a browser?

**Comment by mrmidwest** [comment] 2017-01-31 15:52
When i go to the page in the browser thats the message i get.

**Comment by mrmidwest** [comment] 2017-01-31 15:52
I'm also running this on godaddy.com

**Comment by dlnetworks** [comment] 2017-01-31 17:56
go daddy most likely has outbound connections blocked on the shared host... you can contact go daddy support and request they open the port your radio server runs on.

**Closed as completed** 2017-05-27 10:36 UTC
